version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=sqlite:///./quantumeco.db
      - BLOCKCHAIN_URL=${BLOCKCHAIN_URL}
      - ENABLE_DEMO_MODE=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
